name: citronx
services:
  postgres:
    container_name: citronx_db
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=citronx'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=citronx'
    ports:
      - '5433:5432'
volumes:
  postgres_data:
    driver: local